//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnw.UI.SqlServer.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlConnectionInfoModelRx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlConnectionInfoModelRx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dnw.UI.SqlServer.Models.SqlConnectionInfoModelRx", typeof(SqlConnectionInfoModelRx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has not been specified a file to load data from.
        /// </summary>
        public static string excSCIMNoFileToLoad {
            get {
                return ResourceManager.GetString("excSCIMNoFileToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has not been specified a file where to save the data.
        /// </summary>
        public static string excSCIMNoFileToSave {
            get {
                return ResourceManager.GetString("excSCIMNoFileToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection selected do you want to create one?.
        /// </summary>
        public static string txtSCIMAskToCreateNewConnection {
            get {
                return ResourceManager.GetString("txtSCIMAskToCreateNewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        public static string txtSCIMNewConnection {
            get {
                return ResourceManager.GetString("txtSCIMNewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the currently selected item?.
        /// </summary>
        public static string warSCIMConfirmDeletion {
            get {
                return ResourceManager.GetString("warSCIMConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warTitle {
            get {
                return ResourceManager.GetString("warTitle", resourceCulture);
            }
        }
    }
}
