//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnw.UI.SqlServer.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlConnectionInfoControlRx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlConnectionInfoControlRx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dnw.UI.SqlServer.Controls.SqlConnectionInfoControlRx", typeof(SqlConnectionInfoControlRx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout.
        /// </summary>
        public static string lblSCICCommandTimeout {
            get {
                return ResourceManager.GetString("lblSCICCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionTimeout.
        /// </summary>
        public static string lblSCICConnectionTimeout {
            get {
                return ResourceManager.GetString("lblSCICConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string lblSCICDatabase {
            get {
                return ResourceManager.GetString("lblSCICDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblSCICDescription {
            get {
                return ResourceManager.GetString("lblSCICDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File dati:.
        /// </summary>
        public static string lblSCICFileName {
            get {
                return ResourceManager.GetString("lblSCICFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string lblSCICID {
            get {
                return ResourceManager.GetString("lblSCICID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblSCICPassword {
            get {
                return ResourceManager.GetString("lblSCICPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lblSCICPosition {
            get {
                return ResourceManager.GetString("lblSCICPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string lblSCICServer {
            get {
                return ResourceManager.GetString("lblSCICServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Trusted connection.
        /// </summary>
        public static string lblSCICTrusted {
            get {
                return ResourceManager.GetString("lblSCICTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblSCICType {
            get {
                return ResourceManager.GetString("lblSCICType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblSCICUsername {
            get {
                return ResourceManager.GetString("lblSCICUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clone.
        /// </summary>
        public static string mnuSCICClone {
            get {
                return ResourceManager.GetString("mnuSCICClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string mnuSCICDelete {
            get {
                return ResourceManager.GetString("mnuSCICDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string mnuSCICEdit {
            get {
                return ResourceManager.GetString("mnuSCICEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string mnuSCICExport {
            get {
                return ResourceManager.GetString("mnuSCICExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string mnuSCICImport {
            get {
                return ResourceManager.GetString("mnuSCICImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _New.
        /// </summary>
        public static string mnuSCICNew {
            get {
                return ResourceManager.GetString("mnuSCICNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string mnuSCICUndo {
            get {
                return ResourceManager.GetString("mnuSCICUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection informations.
        /// </summary>
        public static string txtSCICConnDataHeader {
            get {
                return ResourceManager.GetString("txtSCICConnDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert, update or delete the connections information data.
        /// </summary>
        public static string txtSCICMainInstruction {
            get {
                return ResourceManager.GetString("txtSCICMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server specific informations.
        /// </summary>
        public static string txtSCICSqlDataHeader {
            get {
                return ResourceManager.GetString("txtSCICSqlDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data export has not been handled, it is not possible to export the data..
        /// </summary>
        public static string warSCICNoExportDelegate {
            get {
                return ResourceManager.GetString("warSCICNoExportDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data import has not been handled, it is not possible to import the data..
        /// </summary>
        public static string warSCICNoImportDelegate {
            get {
                return ResourceManager.GetString("warSCICNoImportDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warTitle {
            get {
                return ResourceManager.GetString("warTitle", resourceCulture);
            }
        }
    }
}
